#!/bin/sh

# Source tutorial clean functions
. $WM_PROJECT_DIR/bin/tools/CleanFunctions

cleanFilesFromM4 ()
{
    rm -rf constant/polyMesh/boundary > /dev/null 2>&1
    rm -rf constant/polyMesh/blockMeshDict > /dev/null 2>&1
}

cleanTimeZeroAndPV ()
{
    rm -rf 0 > /dev/null 2>&1

    # Clean paraview files
    rm -rf *.foam > /dev/null 2>&1
}

rm -rf points.vtk
rm -rf constant/derivedProperties

cleanFilesFromM4
cleanTimeZeroAndPV
cleanCase
